### PR TITLE
set Maven 3.1.1 as minimum version

### PR DESCRIPTION
**Pull request by elharo**
@michael-o

### CODE REVIEW

**Comment by michael-o** [comment]
Can you please explain why?

**Comment by elharo** [comment]
Toe in the water to move all plugins forward to 3.1 as minimum as discussed on dev. This is the first one I've found where this was actually simple.

**Comment by elharo** [comment]
Test failures might be flaky Jenkins issues, needs investigation:

[INFO] ------------------------------------------------------------------------
[INFO] [jenkins-event-spy] Generated /home/jenkins/jenkins-slave/workspace/maven-box_maven-antrun-plugin_v@2@tmp/withMavenafba2237/maven-spy-20200424-135936-2555145151326151625751.log
[ERROR] unable to create new native thread -> [Help 1]
java.lang.OutOfMemoryError: unable to create new native thread

**Comment by elharo** [comment]
Yep, it was flaky CI. It passed now.

**Comment by rfscholte** [comment]
this should have been 3.1.0. The difference between api and impl is not clear, but as a result of earlier discussions this should the lower version.

**Pull request merged**
